In [1]:
import numpy as np

a = np.arange(12)*12

In [2]:
a

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132])

In [3]:
i = np.array([ 1,1,3,8,5 ])
a[i]

array([12, 12, 36, 96, 60])

In [4]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )  
a[j]

array([[ 36,  48],
       [108,  84]])

In [5]:
palette = np.array( [ [0,0,0],                # black
              [255,0,0],              # red
              [0,255,0],              # green
              [0,0,255],              # blue
              [255,255,255] ] )       # white

In [6]:
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [7]:
image = np.array([[0, 1, 2, 0],[0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [8]:
a = np.arange(12).reshape(3, 4)

In [9]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [11]:
a[b]=0

In [12]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])