In [21]:
import numpy as np

arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr_1 = arr.reshape(3, 5)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr_1.shape

(3, 5)

In [30]:
arr_1.ndim

2

In [31]:
arr_1.size

15

In [32]:
arr_1.itemsize

8

In [33]:
arr_1.data