In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [3]:
a.dtype

dtype('int64')

In [4]:
b = np.array([1.1, 1.2, 1.3])
b.dtype

dtype('float64')

In [5]:
c = np.array([1, 1.1, 1.3])
c.dtype

dtype('float64')

In [7]:
d = np.array([(1, 2, 3), (4, 5,6)])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
e = np.array([(1,2), (3, 4)], dtype=complex)
e

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
e.dtype

dtype('complex128')

In [11]:
f = np.zeros((3, 5))
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
g = np.ones((3, 5), dtype=np.int16)
g

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [13]:
g.dtype

dtype('int16')

In [16]:
h = np.empty((3,10))
h

array([[1.49166815e-154, 1.49166815e-154, 1.18575755e-322,
        0.00000000e+000, 2.12199579e-314, 5.30276956e+180,
        3.31033942e-033, 6.97396532e-076, 3.25510395e-086,
        3.35658658e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.52667914e-052, 1.59894167e+160,
        4.84884775e-033, 1.61899331e-051, 5.56978142e-144,
        1.50008929e+248],
       [7.42621752e-056, 4.25849677e-096, 1.49166815e-154,
        1.49166815e-154, 2.11183321e-052, 4.66726880e-062,
        5.74020278e+180, 8.37174974e-144, 3.24941321e+126,
        2.08600894e-308]])

In [18]:
np.arange(10, 20, 4)

array([10, 14, 18])

In [26]:
np.linspace(0, 4 ,num=5)

array([0., 1., 2., 3., 4.])

In [29]:
from numpy import pi

x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -