In [1]:
import numpy as np

a = np.floor(10*np.random.random((3, 4)))
a

array([[3., 9., 7., 8.],
       [8., 5., 5., 7.],
       [2., 1., 2., 8.]])

In [2]:
a.shape

(3, 4)

In [3]:
a.ravel()

array([3., 9., 7., 8., 8., 5., 5., 7., 2., 1., 2., 8.])

In [4]:
a.reshape(4,3)

array([[3., 9., 7.],
       [8., 8., 5.],
       [5., 7., 2.],
       [1., 2., 8.]])

In [6]:
a.T.shape

(4, 3)

In [7]:
a.T

array([[3., 8., 2.],
       [9., 5., 1.],
       [7., 5., 2.],
       [8., 7., 8.]])

In [8]:
a.resize((2,6))

In [9]:
a.shape

(2, 6)

In [10]:
a.reshape(3, -1)

array([[3., 9., 7., 8.],
       [8., 5., 5., 7.],
       [2., 1., 2., 8.]])

In [12]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
np.vstack((a,b))

array([[1., 6.],
       [5., 1.],
       [5., 9.],
       [8., 8.]])

In [13]:
np.hstack((a,b))

array([[1., 6., 5., 9.],
       [5., 1., 8., 8.]])

In [16]:
a = np.arange(3).reshape(3, 1)

In [21]:
a

array([[0],
       [1],
       [2]])

In [18]:
b = np.arange(3)
b

array([0, 1, 2])