In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.arange(4)
a+b

array([10, 21, 32, 43])

In [2]:
c = a - b
c

array([10, 19, 28, 37])

In [3]:
b**2

array([0, 1, 4, 9])

In [4]:
b*2

array([0, 2, 4, 6])

In [5]:
10*np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [7]:
a < 35

array([ True,  True,  True, False])

In [8]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [9]:
A @ B

array([[5, 4],
       [3, 4]])

In [10]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [12]:
a = np.random.random((2,3))
a

array([[0.05907056, 0.07914644, 0.45223931],
       [0.92910003, 0.18236879, 0.32736631]])

In [13]:
a.sum()

2.029291447002742

In [14]:
a.mean()

0.3382152411671237

In [15]:
a.max()

0.9291000286710553

In [16]:
b = np.arange(12).reshape(4,3)

In [17]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b.sum(axis=0)

array([18, 22, 26])

In [19]:
b.sum(axis=1)

array([ 3, 12, 21, 30])

In [22]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [23]:
a[2]

8

In [24]:
a[2:5]

array([ 8, 27, 64])

In [26]:
a[:6:2] = -1000

In [27]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [28]:
def f(x, y):
    return 10*x + y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [29]:
b[2, 2]

22

In [30]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [31]:
b[0:4, 0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31]])

In [32]:
b[1]

array([10, 11, 12, 13])

In [34]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [35]:
 c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
        [ 10, 12, 13]],
      [[100,101,102],
 [110,112,113]]])

In [36]:
c.shape

(2, 2, 3)

In [37]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [39]:
c[...,1]

array([[  1,  12],
       [101, 112]])

In [40]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [41]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
